name: Python package tools builder
run-name: Build
on:
  push:
    branches:
      - main
jobs:
  package_builder:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/796047098845/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'github-workflows@deepomatic-development-us1.iam.gserviceaccount.com'
          access_token_lifetime: '300s'

      - name: Login to GCP Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://europe-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
